
CREATE TABLE livros
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo VARCHAR(255),
    autor  VARCHAR(255),
    idioma VARCHAR(255),
    CONSTRAINT pk_livros PRIMARY KEY (id)
);
